apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
  namespace: namespace1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
      - name: mi-contenedor
        image: nginx:1.17.1
